name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      scylladb1:
        image: scylladb/scylla:5.2
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        run: cargo clippy --verbose --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose --workspace -- --nocapture
      # - name: Run all tests
      #   run: cargo test --verbose --workspace -- --nocapture --include-ignored
